version: "3"
services:
  api_dev:
    # image: ms-apprein-js:1.0
    build:
      dockerfile: ./buildDocker/development.DockerFile
      context: .
    ports:
      - 5001:5001
    hostname: apireinventing_dev
    restart: always
    volumes:
      # -   ./:/usr/local/nodeapps/
      - /usr/local/volumes/dev_apireinventingpro:/root/.pm2/logs

    command: pm2-runtime server.config.js --env development
    # command: pm2-runtime server.config.js --env production
